# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-67ea9d04-bbf6-4c25-b800-b7823d00e06e";
    fsType = "ext4";
  };

  # STIG V-268144: Protect confidentiality/integrity of data at rest (LUKS encryption)
  boot.initrd.luks.devices."luks-67ea9d04-bbf6-4c25-b800-b7823d00e06e".device =
    "/dev/disk/by-uuid/67ea9d04-bbf6-4c25-b800-b7823d00e06e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0E82-ADBE";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
