# Hardware configuration for Framework Laptop 13 AMD AI 300 Series
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.nixos-hardware.nixosModules.framework-amd-ai-300-series
  ];

  # This will be generated by nixos-generate-config when you install NixOS
  # For now, we'll add a placeholder structure

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cd6631b2-fc6e-41ad-a05c-013a6d42c4f8";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-ee40f3c8-b2b4-4071-b04a-b1b1ddc49113".device =
    "/dev/disk/by-uuid/ee40f3c8-b2b4-4071-b04a-b1b1ddc49113";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E884-F9A2";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
