# Hardware configuration for Framework Laptop 13 AMD AI 300 Series
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    inputs.nixos-hardware.nixosModules.framework-amd-ai-300-series
  ];

  # This will be generated by nixos-generate-config when you install NixOS
  # For now, we'll add a placeholder structure

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Placeholder - will be replaced when you run nixos-generate-config
fileSystems."/" =
    { device = "/dev/disk/by-uuid/54a7d45a-07cc-4395-97d7-2fc8be6168e5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4c1a499b-4fba-40d8-90a0-a803d588eff7".device = "/dev/disk/by-uuid/4c1a499b-4fba-40d8-90a0-a803d588eff7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7057-66ED";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
