name: Format Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - name: Check formatting with treefmt
        run: |
          nix develop --command treefmt --fail-on-change
